### ISSUE TITLE
Plugin crashes the ckeditor

### ISSUE THREAD

**Issue by jayee** [kaltura/sakai-extension#111]
The js error in the console:
plugin.js?t=G87E:17 Uncaught TypeError: CKEDITOR.dialog.addIframe is not a function
 
The kaltura plugin uses CKEDITOR.dialog.addIframe which apparently is not supported in the mobile editor instance.
I also tried upgrading the ckeditor to 4.7.3 with the same result.
 
This is tested with sakai 11.4 and kaltura sakai-extension 5.0.1.

**Comment by kaltura-hooks** [comment]
Hi @jayee,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by idodido** [comment]
Hi @jayee 

thank you for bringing it up - I have asked the team to take a look. 
For purposes of procedure, i would recommend sending future issues directly to our support team at customercare@kaltura.com. This will allow us to track any issue, and will allow the team to reply back in case any issues are need further investigation, and also allow us to make sure items are not lost.

if you would like to get updates on this issue, please contact kaltura customer case, and reference the following ticket ID: SAK-137.

Thanks,
Ido

**Comment by ern** [comment]
See the following Sakai PR that disable plugins on a small devices
https://github.com/sakaiproject/sakai/pull/1788

**Comment by jayee** [comment]
Hi @ern, the problem is that it is not usable in mobile view.
We want it to work in mobile and that is why we added it to mobile view of ckeditor.

I don't know the status for SAK-137 @ kaltura

**Comment by ern** [comment]
Hi @jayee your issue is because in SAK-30370 they disabled all the plugins for devices under 800px if you remove this restriction and load the plugins this error will go away. Your issue is because the iframedialog plugin is not being loaded.
See:
https://github.com/sakaiproject/sakai/blob/3848c2b894e9a601fe43c8ed8acbd2580b2f87d2/library/src/webapp-filtered/editor/ckeditor.launch.js#L240

Again this is just a configuration issue where if you were to properly configure ckeditor to load the correct plugins it would work.

**Comment by jayee** [comment]
Thank you Earle!

We will look into enabling the plugins.

mån 5 feb. 2018 kl 15:20 skrev Earle Nietzel <notifications@github.com>:
