### ISSUE TITLE
KAF not respecting LTI property launch_presentation_locale

### ISSUE THREAD

**Issue by jonevn** [kaltura/sakai-extension#114]
When using My Media the language does not follow the one selected in Sakai. In our instance we have support for both Swedish and English, but only English gets showed from the KAF. I can see that we send launch_presentation_locale = sv_SE, but this is ignored.

Also, when sending lti-request to /my-media I can see in the logs on the KAF:
Not a LTI request - failing launcher

**Comment by kaltura-hooks** [comment]
Hi @jonevn,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by idodido** [comment]
Hi @jonevn 

Please reach out to Kaltura customer care team at Customercare@kaltura.com they should be able to help. 

However, before you do that, i would verify that you set the languages module in your KAF application. 
in your KAF admin, navigate to https://xxxxxxx.kaf.kaltura.com/admin/config/tab/application (change xxxxxxx to your KAF instance) make sure that languageConfiguration is set to 'Multi Language Instance'. then check under languageSelection the desired languages. 

if the above is indeed set, and the My-media language does not change according to the sakai language, Kaltura customer care should be able to assist.

regards.

**Comment by jonevn** [comment]
Thanks for the answer. After looking more into the problem I found that we have modified the plugin to send language and country (sv_SE or en_US), but that doesn't work. Changed it now to send only language (sv or en) and now it works. I am new to our project and didn't know that we had locally modified the code.
