### ISSUE TITLE
Get changes into Sakai upstream AntiSamy policy

### ISSUE THREAD

**Issue by ottenhoff** [kaltura/sakai-extension#93]
Docs say:

```

#antisamy will remove src entries in <iframe> tags by default for Kaltura, as that
#domain is not registered in the high security policy
```

What "domain is not registered"? Let's add it to sakaiproject antisamy XML files.

**Comment by kaltura-hooks** [comment]
Hi @ottenhoff,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by gonenradai** [comment]
@ottenhoff 
The KAF domain is the one that will be used inside the rich text editor content.
The KAF domain could be different per customer.

Most would probably be using a Kaltura-hosted KAF instance, and so the domain would be in the form of {number}.kaf.kaltura.com
where the number changes between customers.
Others may choose to use Kaltura-hosted KAF but with their own alias (for example kaf-sakai.school.edu, or any other chosen prefix under school.edu) or have KAF part of their Kaltura On-Prem deployment (in which case I can't even say what the domain would look like).

Adding *.kaf.kaltura.com to sakaiproject antisamy XML files would most likely be a good thing to follow 80/20 rule.

**Comment by ottenhoff** [comment]
Thanks I will submit a PR to sakaiproject getting *.kaf.kaltura.com whitelisted!
